### ISSUE TITLE
Riffle shuffle and event handling

### ISSUE THREAD

**Issue by JoelIsAGit** [RedCore0/Assessment-1-Object-Oriented-Programming#1]
Love the code, overall it's neat and easy to read, the code is short and efficient it seems.

Looks like the set methods in the card class doesn't involve any validation, changing the value to private and adding public Set methods would help stop cards becoming impossible values, 

The DealCard(int Amount) function could use the DealCard() function to save on rewriting some code, cards are already being removed and written in that DealCard() function anyways.

Looks like the riffle shuffle always returns the same values, the perfect riffle shuffle would do this however it's not useful in the context of a shuffling and dealing application since players would always have the same cards.

To be fair the perfect riffle shuffle would give that functions outcome so I wouldn't say it's necessarily wrong.

Overall it's good code and generally there aren't things I would change beyond what's above.

**Comment by RedCore0** [comment]
Thanks for feedback, I've done some changes to the code
