### ISSUE TITLE
Code review - Dasha

### ISSUE THREAD

**Issue by Bella-Dragonborn** [RedCore0/Assessment-1-Object-Oriented-Programming#2]
Hi Michal! 

I reviewed your code and it looks pretty good. It is easy to read and understand it. 

There are two issues that I found.
1. When you are creating your first pack, you immediately show it, which is not necessary.
2. You created a code for Riffle Shuffle inside TypeOfShuffle class and outside it. Second part - here:
![image](https://user-images.githubusercontent.com/126836282/223883124-efb12818-0cbe-4042-869c-1f8e12e9db49.png)
you could put it in TypeOfShuffle code.

Everything else looks good.

**Comment by RedCore0** [comment]
Thanks for feedback, I've done some changes to my code
